@include("layouts.partials.head")
@include("layouts.partials.nav")
<body>
    @include('layouts.partials.errors')
    @include('layouts.partials.success')
    @yield('content')
    @include('layouts.partials.js')
</body>
</html>